spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Martinfreeman
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: IdentityHikariPool
      auto-commit: false
      connection-timeout: 10000
      idle-timeout: 60000
      max-lifetime: 120000
      minimum-idle: 5
      maximum-pool-size: 10
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create

file:
  upload:
    image-root-directory: src/main/resources/image/
    acceptable-extension: png,jpg,jpeg

cors:
  allow:
    origin:
      hr-portal: "*"

security:
  day-init-key: 8XoI7_-lF1JarJ0VY9ttRNPbL-cmPSdpYgAUa1sK
  jwt:
    base64-secret: eUlKUFpFUjJkdEVtNDg0UUR5UDAxNlRWSnlLVnZMU1R0WkZtM0VzRzh6Y2ZQSm5TRXRQQjQzdk5vOGRGdEdzSlk1clV1RDlvSVFuVGtLeE9QMm96aHBzdWZDbzE2M0dWN2VWZ2JRT014SllIOWRRaFdm
    access-token-validity-in-milliseconds: 60000

application:
  swagger:
    title: Swagger HrPortal WebSite
    description: The api is used for YouDoIt website
    version: 1.0.0

logging:
  file:
    name: "./logs/hr_info_log.log"
  level:
    ROOT: INFO
  pattern:
    file: "[ %p ] %d{yyyy-MM-dd HH:mm:ss} [THREAD - %t] %-5p %c:%L - %m%n"
server:
  port: 8080
