spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Martinfreeman
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: IdentityHikariPool
      auto-commit: false
      connection-timeout: 10000
      idle-timeout: 60000
      max-lifetime: 120000
      minimum-idle: 5
      maximum-pool-size: 10
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create

application:
  swagger:
    title: Swagger BirBank WebSite
    description: The api is used for birbank.az website
    version: 1.0.0