server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  datasource:
    url: jdbc:postgresql://ec2-35-169-188-58.compute-1.amazonaws.com:5432/db4sfsihpa5fmr
    username: jhrvoevrtbttsy
    password: 9e4efe465ffbd6caaba93b898f81960a6d91874a1644142b04946435d62445ba
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: Martinfreeman2001
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: IdentityHikariPool
      auto-commit: false
      connection-timeout: 10000
      idle-timeout: 60000
      max-lifetime: 120000
      minimum-idle: 5
      maximum-pool-size: 10
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update

file:
  upload:
    image-root-directory: src/main/resources/image/
    acceptable-extension: png,jpg,jpeg

cors:
  allow:
    origin:
      hr-portal: "*"

security:
  day-init-key: 8XoI7_-lF1JarJ0VY9ttRNPbL-cmPSdpYgAUa1sK
  jwt:
    base64-secret: eUlKUFpFUjJkdEVtNDg0UUR5UDAxNlRWSnlLVnZMU1R0WkZtM0VzRzh6Y2ZQSm5TRXRQQjQzdk5vOGRGdEdzSlk1clV1RDlvSVFuVGtLeE9QMm96aHBzdWZDbzE2M0dWN2VWZ2JRT014SllIOWRRaFdm
    access-token-validity-in-milliseconds: 60000

application:
  swagger:
    title: Swagger HrPortal WebSite
    description: The api is used for YouDoIt website
    version: 1.0.0

logging:
  file:
    name: "${catalina.base}/logs/hr_info_logs/hr_info_log.log"
  level:
    ROOT: INFO
  pattern:
    file: "[ %p ] %d{yyyy-MM-dd HH:mm:ss, Asia/Baku} [THREAD - %t] %-5p %c:%L - %m%n"
    console: "[ %p ] %d{yyyy-MM-dd HH:mm:ss, Asia/Baku} [THREAD - %t] %-5p %c:%L - %m%n"

filter:
  url:
    csp: "script-src 'self' https://trustedscripts.example.com; object-src https://trustedplugins.example.com; report-uri /csp-report-endpoint/"
    ignore: /error,/favicon.ico,/,/csrf,/actuator/**,/swagger-ui.html,/app/**/*.{js,html},/i18n/**,/content/**,/swagger-ui/index.html,/v2/api-docs,/webjars/**,/swagger-resources/**

amazon:
  s3:
    bucket:
      hr-portal: hr-file-storage
      folder:
        employee-images: employee-images
    access-key: AKIA4KJG2K4QRMASSY7V
    secret-key: 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