spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Martinfreeman
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: IdentityHikariPool
      auto-commit: false
      connection-timeout: 10000
      idle-timeout: 60000
      max-lifetime: 120000
      minimum-idle: 5
      maximum-pool-size: 10
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update

file:
  upload:
    root-directory: src/main/resources/image/

cors:
  allow:
    origin:
      hr-portal: "*"

security:
  jwt:
    base64-secret: eUlKUFpFUjJkdEVtNDg0UUR5UDAxNlRWSnlLVnZMU1R0WkZtM0VzRzh6Y2ZQSm5TRXRQQjQzdk5vOGRGdEdzSlk1clV1RDlvSVFuVGtLeE9QMm96aHBzdWZDbzE2M0dWN2VWZ2JRT014SllIOWRRaFdm
    access-token-validity-in-milliseconds: 60000

application:
  swagger:
    title: Swagger BirBank WebSite
    description: The api is used for birbank.az website
    version: 1.0.0